#!/usr/bin/expect

# Configuration
set timeout 300
set host "93.127.206.52"
set user "root"
set password "Royal300@2026"
set script "./deploy.sh"

# Wait, the script *is* deploy.sh, but ssh uses password.
# However, deploy.sh runs commands locally then shells out.
# So I should spawn the ssh session directly? 
# No, deploy.sh executes tasks. Let's just wrap deploy.sh execution.

spawn $script

expect {
    "Are you sure you want to continue connecting" {
        send "yes\r"
        exp_continue
    }
    "password:" {
        send "$password\r"
    }
}

interact
