
#!/usr/bin/expect

# Configuration
set timeout 300
set host $env(DEPLOY_HOST)
set user $env(DEPLOY_USER)
set password $env(DEPLOY_PASSWORD)
set script "./deploy.sh"

spawn $script

expect {
    "Are you sure you want to continue connecting" {
        send "yes\r"
        exp_continue
    }
    "password:" {
        send "$password\r"
        exp_continue
    }
    eof
}

puts "\n🎉 Deployment finished!"
